# Generated by Django 4.1.5 on 2023-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about_comment_portfolio_service_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='company',
            field=models.CharField(default='', max_length=30),
        ),
    ]
