# Generated by Django 4.1.5 on 2023-06-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_about_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('university', models.CharField(default='', max_length=30)),
                ('icon', models.TextField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
