# Generated by Django 4.1.5 on 2023-06-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_service_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
    ]
