# Generated by Django 4.1.5 on 2023-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_project',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='preview',
            field=models.CharField(default='', max_length=50),
        ),
    ]
